### ISSUE TITLE
Could EnQA be used for the evaluation of protein complexes?

### ISSUE THREAD

**Issue by onlyonewater** [BioinfoMachineLearning/EnQA#5]
Could EnQA be used for the evaluation of protein complexes?

**Comment by jianlin-cheng** [comment]
Theoretically, EnQA with some minor modification can be used to predict the
quality of protein complexes. Some code needs to be changed to treat
multiple chains in a complex as a single chain while not connecting the
last amino acid of a chain and the first amino acid of the following chain
as two adjacent amino acids on the same chain. We hope to add this function
in the future.

**Comment by chrischen1** [comment]
For EnQA, you can provide protein complexes as input, and no additional work is required. 
For EnQA-MSA, you can preprocess the input PDB with the [mergePDB](https://github.com/BioinfoMachineLearning/EnQA/blob/25c1142fa8936ebb843db79a51161cdee499697a/data/process_alphafold.py#L139) function we provided to convert it into a "merged single chain PDB" and make that as the input PDB. Then run EnQA-MSA in the same way as single chain inputs.

**Comment by onlyonewater** [comment]
OK, thanks!!, I get it, I will have a try!!!

**Comment by onlyonewater** [comment]
And Does the current code support training the EnQA from scratch?

**Comment by chrischen1** [comment]
Yes, please refer to the latest updates to the readme.
https://github.com/BioinfoMachineLearning/EnQA#model-training-for-enqa-msa
https://github.com/BioinfoMachineLearning/EnQA#model-training-for-enqa-assisted-with-alphafold2

**Comment by onlyonewater** [comment]
ok, thanks!!!
